# Generated by Django 4.1 on 2022-08-28 08:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=30, verbose_name="Full Name"),
                ),
                ("number", models.IntegerField(verbose_name="Number")),
                (
                    "mobile",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("1", "Female"),
                            ("2", "Male"),
                            ("3", "Other"),
                            ("4", "Prefer not to say"),
                        ],
                        max_length=30,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        choices=[
                            ("1", "Full Stack"),
                            ("2", "Data Science"),
                            ("3", "DevOps"),
                            ("4", "AWS"),
                            ("5", "ITF"),
                        ],
                        max_length=30,
                        verbose_name="Path",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
    ]
